### PR TITLE
Add support for accounts, applications, proxy and proxy configs APIs

### PR DESCRIPTION
**Pull request by ffiore**
Added the following commands and sub-commands:
- accounts (list, show)
- applications (create, list, show, update, delete, suspend, resume)
- proxy (update, show)
- proxy-configs (list, show, promote)

Also added the `services delete` sub-command.

### CODE REVIEW

**Comment by david-martin** [comment]
@picsoung This would be good to get into the cli.
It has most of what I'm looking for that's currently missing on master.

The only things its missing for me then would be:
* Proxy Config Show Latest - GET /admin/api/services/{service_id}/proxy/configs/{environment}/latest.json
* Application Key Create - POST /admin/api/accounts/{account_id}/applications/{application_id}/keys.xml

But I could look at adding them too based on this PR if its merged.

**Comment by picsoung** [comment]
Nice work @ffiore !

Somehow I missed this PR. thanks @david-martin  for the heads up

@3scale/support do you want to give it a look?

**Comment by kevprice83** [comment]
@picsoung i’ll take a look next week.

**Comment by picsoung** [comment]
@kevprice83 do you have any update on this ? :)

**Comment by ioggstream** [comment]
Good work @ffiore . Rock!

**Pull request merged**
